@AdvertisingService_HostAddress = http://localhost:5072

### Загрузить данные из файла
POST {{AdvertisingService_HostAddress}}/advertising/load
Content-Type: application/json

{
  "filePath": "platforms.txt"
}

### Получить рекламные площадки для локации
GET {{AdvertisingService_HostAddress}}/advertising/platforms?location=/ru/msk
Accept: application/json

### Получить рекламные площадки для другой локации
GET {{AdvertisingService_HostAddress}}/advertising/platforms?location=/ru/svrd
Accept: application/json

